<footer id="footer" class="wrapper">
  <div class="inner">
    <div id="footer-copyright">
      &copy; {{ moment(Date.now()).year() }} <a href="/" target="_blank">m2 Referral</a>. All Rights Reserved.<br>
      <a href="http://www.m2ecommerce.com/disclaimer/" target="_blank">Disclaimer</a> | <a href="http://www.m2ecommerce.com/privacy-policy/" target="_blank">Privacy Policy</a>.
    </div>
    <div id="footer-links">
      <a href="https://twitter.com/m2ecommerce" class="footer-link" target="_blank"><i class="fa fa-twitter"></i></a>
      <a href="https://www.facebook.com/m2ecommerce" class="footer-link" target="_blank"><i class="fa fa-facebook-f"></i></a>
    </div>
  </div>
</footer>
